//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TimeFlies.Data", "FK_Images_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TimeFlies.Data.AppUser), "Images", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TimeFlies.Data.Images), true)]
[assembly: EdmRelationshipAttribute("TimeFlies.Data", "FK_Images_Videos", "Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TimeFlies.Data.Videos), "Images", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TimeFlies.Data.Images), true)]
[assembly: EdmRelationshipAttribute("TimeFlies.Data", "FK_Videos_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TimeFlies.Data.AppUser), "Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TimeFlies.Data.Videos), true)]

#endregion

namespace TimeFlies.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TimeFliesByEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TimeFliesByEntities object using the connection string found in the 'TimeFliesByEntities' section of the application configuration file.
        /// </summary>
        public TimeFliesByEntities() : base("name=TimeFliesByEntities", "TimeFliesByEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TimeFliesByEntities object.
        /// </summary>
        public TimeFliesByEntities(string connectionString) : base(connectionString, "TimeFliesByEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TimeFliesByEntities object.
        /// </summary>
        public TimeFliesByEntities(EntityConnection connection) : base(connection, "TimeFliesByEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Images> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Images>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Images> _Images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppUser> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<AppUser>("User");
                }
                return _User;
            }
        }
        private ObjectSet<AppUser> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Videos> Videos
        {
            get
            {
                if ((_Videos == null))
                {
                    _Videos = base.CreateObjectSet<Videos>("Videos");
                }
                return _Videos;
            }
        }
        private ObjectSet<Videos> _Videos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Images images)
        {
            base.AddObject("Images", images);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(AppUser appUser)
        {
            base.AddObject("User", appUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Videos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideos(Videos videos)
        {
            base.AddObject("Videos", videos);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TimeFlies.Data", Name="AppUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppUser object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="isYoutube">Initial value of the IsYoutube property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        public static AppUser CreateAppUser(global::System.String userId, global::System.String email, global::System.Boolean isYoutube, global::System.Boolean isActive, global::System.DateTime dateAdded)
        {
            AppUser appUser = new AppUser();
            appUser.UserId = userId;
            appUser.Email = email;
            appUser.IsYoutube = isYoutube;
            appUser.IsActive = isActive;
            appUser.DateAdded = dateAdded;
            return appUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YoutubeId
        {
            get
            {
                return _YoutubeId;
            }
            set
            {
                OnYoutubeIdChanging(value);
                ReportPropertyChanging("YoutubeId");
                _YoutubeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YoutubeId");
                OnYoutubeIdChanged();
            }
        }
        private global::System.String _YoutubeId;
        partial void OnYoutubeIdChanging(global::System.String value);
        partial void OnYoutubeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YoutubePass
        {
            get
            {
                return _YoutubePass;
            }
            set
            {
                OnYoutubePassChanging(value);
                ReportPropertyChanging("YoutubePass");
                _YoutubePass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YoutubePass");
                OnYoutubePassChanged();
            }
        }
        private global::System.String _YoutubePass;
        partial void OnYoutubePassChanging(global::System.String value);
        partial void OnYoutubePassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YoutubeVideoId
        {
            get
            {
                return _YoutubeVideoId;
            }
            set
            {
                OnYoutubeVideoIdChanging(value);
                ReportPropertyChanging("YoutubeVideoId");
                _YoutubeVideoId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YoutubeVideoId");
                OnYoutubeVideoIdChanged();
            }
        }
        private global::System.String _YoutubeVideoId;
        partial void OnYoutubeVideoIdChanging(global::System.String value);
        partial void OnYoutubeVideoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsYoutube
        {
            get
            {
                return _IsYoutube;
            }
            set
            {
                OnIsYoutubeChanging(value);
                ReportPropertyChanging("IsYoutube");
                _IsYoutube = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsYoutube");
                OnIsYoutubeChanged();
            }
        }
        private global::System.Boolean _IsYoutube;
        partial void OnIsYoutubeChanging(global::System.Boolean value);
        partial void OnIsYoutubeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RightEye
        {
            get
            {
                return _RightEye;
            }
            set
            {
                OnRightEyeChanging(value);
                ReportPropertyChanging("RightEye");
                _RightEye = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RightEye");
                OnRightEyeChanged();
            }
        }
        private global::System.String _RightEye;
        partial void OnRightEyeChanging(global::System.String value);
        partial void OnRightEyeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LeftEye
        {
            get
            {
                return _LeftEye;
            }
            set
            {
                OnLeftEyeChanging(value);
                ReportPropertyChanging("LeftEye");
                _LeftEye = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LeftEye");
                OnLeftEyeChanged();
            }
        }
        private global::System.String _LeftEye;
        partial void OnLeftEyeChanging(global::System.String value);
        partial void OnLeftEyeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccessToken
        {
            get
            {
                return _AccessToken;
            }
            set
            {
                OnAccessTokenChanging(value);
                ReportPropertyChanging("AccessToken");
                _AccessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccessToken");
                OnAccessTokenChanged();
            }
        }
        private global::System.String _AccessToken;
        partial void OnAccessTokenChanging(global::System.String value);
        partial void OnAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BrowseId
        {
            get
            {
                return _BrowseId;
            }
            set
            {
                OnBrowseIdChanging(value);
                ReportPropertyChanging("BrowseId");
                _BrowseId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BrowseId");
                OnBrowseIdChanged();
            }
        }
        private global::System.String _BrowseId;
        partial void OnBrowseIdChanging(global::System.String value);
        partial void OnBrowseIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Images_User", "Images")]
        public EntityCollection<Images> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Images>("TimeFlies.Data.FK_Images_User", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Images>("TimeFlies.Data.FK_Images_User", "Images", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Videos_User", "Videos")]
        public EntityCollection<Videos> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Videos>("TimeFlies.Data.FK_Videos_User", "Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Videos>("TimeFlies.Data.FK_Videos_User", "Videos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TimeFlies.Data", Name="Images")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Images : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Images object.
        /// </summary>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        /// <param name="isRead">Initial value of the IsRead property.</param>
        /// <param name="isEdit">Initial value of the IsEdit property.</param>
        /// <param name="isDelete">Initial value of the IsDelete property.</param>
        /// <param name="isReSeq">Initial value of the IsReSeq property.</param>
        /// <param name="isInvalid">Initial value of the IsInvalid property.</param>
        public static Images CreateImages(global::System.Int32 imageId, global::System.String userId, global::System.DateTime dateAdded, global::System.Boolean isRead, global::System.Boolean isEdit, global::System.Boolean isDelete, global::System.Boolean isReSeq, global::System.Boolean isInvalid)
        {
            Images images = new Images();
            images.ImageId = imageId;
            images.UserId = userId;
            images.DateAdded = dateAdded;
            images.IsRead = isRead;
            images.IsEdit = isEdit;
            images.IsDelete = isDelete;
            images.IsReSeq = isReSeq;
            images.IsInvalid = isInvalid;
            return images;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                if (_ImageId != value)
                {
                    OnImageIdChanging(value);
                    ReportPropertyChanging("ImageId");
                    _ImageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageId");
                    OnImageIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VideoId
        {
            get
            {
                return _VideoId;
            }
            set
            {
                OnVideoIdChanging(value);
                ReportPropertyChanging("VideoId");
                _VideoId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VideoId");
                OnVideoIdChanged();
            }
        }
        private global::System.String _VideoId;
        partial void OnVideoIdChanging(global::System.String value);
        partial void OnVideoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageName
        {
            get
            {
                return _ImageName;
            }
            set
            {
                OnImageNameChanging(value);
                ReportPropertyChanging("ImageName");
                _ImageName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageName");
                OnImageNameChanged();
            }
        }
        private global::System.String _ImageName;
        partial void OnImageNameChanging(global::System.String value);
        partial void OnImageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThumbPath
        {
            get
            {
                return _ThumbPath;
            }
            set
            {
                OnThumbPathChanging(value);
                ReportPropertyChanging("ThumbPath");
                _ThumbPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbPath");
                OnThumbPathChanged();
            }
        }
        private global::System.String _ThumbPath;
        partial void OnThumbPathChanging(global::System.String value);
        partial void OnThumbPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRead
        {
            get
            {
                return _IsRead;
            }
            set
            {
                OnIsReadChanging(value);
                ReportPropertyChanging("IsRead");
                _IsRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRead");
                OnIsReadChanged();
            }
        }
        private global::System.Boolean _IsRead;
        partial void OnIsReadChanging(global::System.Boolean value);
        partial void OnIsReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEdit
        {
            get
            {
                return _IsEdit;
            }
            set
            {
                OnIsEditChanging(value);
                ReportPropertyChanging("IsEdit");
                _IsEdit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEdit");
                OnIsEditChanged();
            }
        }
        private global::System.Boolean _IsEdit;
        partial void OnIsEditChanging(global::System.Boolean value);
        partial void OnIsEditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDelete
        {
            get
            {
                return _IsDelete;
            }
            set
            {
                OnIsDeleteChanging(value);
                ReportPropertyChanging("IsDelete");
                _IsDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelete");
                OnIsDeleteChanged();
            }
        }
        private global::System.Boolean _IsDelete;
        partial void OnIsDeleteChanging(global::System.Boolean value);
        partial void OnIsDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReSeq
        {
            get
            {
                return _IsReSeq;
            }
            set
            {
                OnIsReSeqChanging(value);
                ReportPropertyChanging("IsReSeq");
                _IsReSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReSeq");
                OnIsReSeqChanged();
            }
        }
        private global::System.Boolean _IsReSeq;
        partial void OnIsReSeqChanging(global::System.Boolean value);
        partial void OnIsReSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInvalid
        {
            get
            {
                return _IsInvalid;
            }
            set
            {
                OnIsInvalidChanging(value);
                ReportPropertyChanging("IsInvalid");
                _IsInvalid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInvalid");
                OnIsInvalidChanged();
            }
        }
        private global::System.Boolean _IsInvalid;
        partial void OnIsInvalidChanging(global::System.Boolean value);
        partial void OnIsInvalidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Images_User", "User")]
        public AppUser User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Images_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Images_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AppUser> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Images_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AppUser>("TimeFlies.Data.FK_Images_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Images_Videos", "Videos")]
        public Videos Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Videos>("TimeFlies.Data.FK_Images_Videos", "Videos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Videos>("TimeFlies.Data.FK_Images_Videos", "Videos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Videos> VideosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Videos>("TimeFlies.Data.FK_Images_Videos", "Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Videos>("TimeFlies.Data.FK_Images_Videos", "Videos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TimeFlies.Data", Name="Videos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Videos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Videos object.
        /// </summary>
        /// <param name="videoId">Initial value of the VideoId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="isReminder">Initial value of the IsReminder property.</param>
        /// <param name="isSentReminder">Initial value of the IsSentReminder property.</param>
        /// <param name="isCompile">Initial value of the IsCompile property.</param>
        /// <param name="isError">Initial value of the IsError property.</param>
        /// <param name="isImage">Initial value of the IsImage property.</param>
        /// <param name="isSoundTrack">Initial value of the IsSoundTrack property.</param>
        /// <param name="isUploadToYouTube">Initial value of the IsUploadToYouTube property.</param>
        /// <param name="views">Initial value of the Views property.</param>
        public static Videos CreateVideos(global::System.String videoId, global::System.String userId, global::System.Boolean isReminder, global::System.Boolean isSentReminder, global::System.Boolean isCompile, global::System.Boolean isError, global::System.Boolean isImage, global::System.Boolean isSoundTrack, global::System.Boolean isUploadToYouTube, global::System.Int32 views)
        {
            Videos videos = new Videos();
            videos.VideoId = videoId;
            videos.UserId = userId;
            videos.IsReminder = isReminder;
            videos.IsSentReminder = isSentReminder;
            videos.IsCompile = isCompile;
            videos.IsError = isError;
            videos.IsImage = isImage;
            videos.IsSoundTrack = isSoundTrack;
            videos.IsUploadToYouTube = isUploadToYouTube;
            videos.Views = views;
            return videos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VideoId
        {
            get
            {
                return _VideoId;
            }
            set
            {
                if (_VideoId != value)
                {
                    OnVideoIdChanging(value);
                    ReportPropertyChanging("VideoId");
                    _VideoId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VideoId");
                    OnVideoIdChanged();
                }
            }
        }
        private global::System.String _VideoId;
        partial void OnVideoIdChanging(global::System.String value);
        partial void OnVideoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VideoName
        {
            get
            {
                return _VideoName;
            }
            set
            {
                OnVideoNameChanging(value);
                ReportPropertyChanging("VideoName");
                _VideoName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VideoName");
                OnVideoNameChanged();
            }
        }
        private global::System.String _VideoName;
        partial void OnVideoNameChanging(global::System.String value);
        partial void OnVideoNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UserReminderTime
        {
            get
            {
                return _UserReminderTime;
            }
            set
            {
                OnUserReminderTimeChanging(value);
                ReportPropertyChanging("UserReminderTime");
                _UserReminderTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserReminderTime");
                OnUserReminderTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UserReminderTime;
        partial void OnUserReminderTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUserReminderTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ServerReminderTime
        {
            get
            {
                return _ServerReminderTime;
            }
            set
            {
                OnServerReminderTimeChanging(value);
                ReportPropertyChanging("ServerReminderTime");
                _ServerReminderTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServerReminderTime");
                OnServerReminderTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ServerReminderTime;
        partial void OnServerReminderTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnServerReminderTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeZone
        {
            get
            {
                return _TimeZone;
            }
            set
            {
                OnTimeZoneChanging(value);
                ReportPropertyChanging("TimeZone");
                _TimeZone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeZone");
                OnTimeZoneChanged();
            }
        }
        private global::System.String _TimeZone;
        partial void OnTimeZoneChanging(global::System.String value);
        partial void OnTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateAdded;
        partial void OnDateAddedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReminder
        {
            get
            {
                return _IsReminder;
            }
            set
            {
                OnIsReminderChanging(value);
                ReportPropertyChanging("IsReminder");
                _IsReminder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReminder");
                OnIsReminderChanged();
            }
        }
        private global::System.Boolean _IsReminder;
        partial void OnIsReminderChanging(global::System.Boolean value);
        partial void OnIsReminderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSentReminder
        {
            get
            {
                return _IsSentReminder;
            }
            set
            {
                OnIsSentReminderChanging(value);
                ReportPropertyChanging("IsSentReminder");
                _IsSentReminder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSentReminder");
                OnIsSentReminderChanged();
            }
        }
        private global::System.Boolean _IsSentReminder;
        partial void OnIsSentReminderChanging(global::System.Boolean value);
        partial void OnIsSentReminderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EncodedVideoPath
        {
            get
            {
                return _EncodedVideoPath;
            }
            set
            {
                OnEncodedVideoPathChanging(value);
                ReportPropertyChanging("EncodedVideoPath");
                _EncodedVideoPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EncodedVideoPath");
                OnEncodedVideoPathChanged();
            }
        }
        private global::System.String _EncodedVideoPath;
        partial void OnEncodedVideoPathChanging(global::System.String value);
        partial void OnEncodedVideoPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.String _Duration;
        partial void OnDurationChanging(global::System.String value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCompile
        {
            get
            {
                return _IsCompile;
            }
            set
            {
                OnIsCompileChanging(value);
                ReportPropertyChanging("IsCompile");
                _IsCompile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCompile");
                OnIsCompileChanged();
            }
        }
        private global::System.Boolean _IsCompile;
        partial void OnIsCompileChanging(global::System.Boolean value);
        partial void OnIsCompileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsError
        {
            get
            {
                return _IsError;
            }
            set
            {
                OnIsErrorChanging(value);
                ReportPropertyChanging("IsError");
                _IsError = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsError");
                OnIsErrorChanged();
            }
        }
        private global::System.Boolean _IsError;
        partial void OnIsErrorChanging(global::System.Boolean value);
        partial void OnIsErrorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorDescription
        {
            get
            {
                return _ErrorDescription;
            }
            set
            {
                OnErrorDescriptionChanging(value);
                ReportPropertyChanging("ErrorDescription");
                _ErrorDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorDescription");
                OnErrorDescriptionChanged();
            }
        }
        private global::System.String _ErrorDescription;
        partial void OnErrorDescriptionChanging(global::System.String value);
        partial void OnErrorDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsImage
        {
            get
            {
                return _IsImage;
            }
            set
            {
                OnIsImageChanging(value);
                ReportPropertyChanging("IsImage");
                _IsImage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsImage");
                OnIsImageChanged();
            }
        }
        private global::System.Boolean _IsImage;
        partial void OnIsImageChanging(global::System.Boolean value);
        partial void OnIsImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSoundTrack
        {
            get
            {
                return _IsSoundTrack;
            }
            set
            {
                OnIsSoundTrackChanging(value);
                ReportPropertyChanging("IsSoundTrack");
                _IsSoundTrack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSoundTrack");
                OnIsSoundTrackChanged();
            }
        }
        private global::System.Boolean _IsSoundTrack;
        partial void OnIsSoundTrackChanging(global::System.Boolean value);
        partial void OnIsSoundTrackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoundTrackPath
        {
            get
            {
                return _SoundTrackPath;
            }
            set
            {
                OnSoundTrackPathChanging(value);
                ReportPropertyChanging("SoundTrackPath");
                _SoundTrackPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoundTrackPath");
                OnSoundTrackPathChanged();
            }
        }
        private global::System.String _SoundTrackPath;
        partial void OnSoundTrackPathChanging(global::System.String value);
        partial void OnSoundTrackPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUploadToYouTube
        {
            get
            {
                return _IsUploadToYouTube;
            }
            set
            {
                OnIsUploadToYouTubeChanging(value);
                ReportPropertyChanging("IsUploadToYouTube");
                _IsUploadToYouTube = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUploadToYouTube");
                OnIsUploadToYouTubeChanged();
            }
        }
        private global::System.Boolean _IsUploadToYouTube;
        partial void OnIsUploadToYouTubeChanging(global::System.Boolean value);
        partial void OnIsUploadToYouTubeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publish
        {
            get
            {
                return _Publish;
            }
            set
            {
                OnPublishChanging(value);
                ReportPropertyChanging("Publish");
                _Publish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Publish");
                OnPublishChanged();
            }
        }
        private global::System.String _Publish;
        partial void OnPublishChanging(global::System.String value);
        partial void OnPublishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Views
        {
            get
            {
                return _Views;
            }
            set
            {
                OnViewsChanging(value);
                ReportPropertyChanging("Views");
                _Views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Views");
                OnViewsChanged();
            }
        }
        private global::System.Int32 _Views;
        partial void OnViewsChanging(global::System.Int32 value);
        partial void OnViewsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Images_Videos", "Images")]
        public EntityCollection<Images> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Images>("TimeFlies.Data.FK_Images_Videos", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Images>("TimeFlies.Data.FK_Images_Videos", "Images", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimeFlies.Data", "FK_Videos_User", "User")]
        public AppUser User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Videos_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Videos_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AppUser> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppUser>("TimeFlies.Data.FK_Videos_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AppUser>("TimeFlies.Data.FK_Videos_User", "User", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TimeFlies.Data", Name="ComplexType1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ComplexType1 : ComplexObject
    {
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TimeFlies.Data", Name="ComplexType2")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ComplexType2 : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComplexType2 object.
        /// </summary>
        /// <param name="property1">Initial value of the Property1 property.</param>
        public static ComplexType2 CreateComplexType2(global::System.Boolean property1)
        {
            ComplexType2 complexType2 = new ComplexType2();
            complexType2.Property1 = property1;
            return complexType2;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Property1
        {
            get
            {
                return _Property1;
            }
            set
            {
                OnProperty1Changing(value);
                ReportPropertyChanging("Property1");
                _Property1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property1");
                OnProperty1Changed();
            }
        }
        private global::System.Boolean _Property1;
        partial void OnProperty1Changing(global::System.Boolean value);
        partial void OnProperty1Changed();

        #endregion

    }

    #endregion

    
}
